/**
 * Localization Helper - Yemen App
 */
class Localization {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'appTitle': 'Yemen Shipping',
      'login': 'Login',
      'username': 'Username',
      'password': 'Password',
      'loginButton': 'Sign In',
      'logout': 'Logout',
      'home': 'Home',
      'dashboard': 'Dashboard',
      'shipments': 'Shipments',
      'customers': 'Customers',
      'customs': 'Customs',
      'delivery': 'Delivery',
      'collections': 'Collections',
      'tracking': 'Tracking',
      'settings': 'Settings',
      'profile': 'Profile',
      'language': 'Language',
      'incomingShipments': 'Incoming Shipments',
      'shipmentDetails': 'Shipment Details',
      'shipmentNumber': 'Shipment Number',
      'status': 'Status',
      'customer': 'Customer',
      'origin': 'Origin Port',
      'destination': 'Destination Port',
      'vessel': 'Vessel',
      'departureDate': 'Departure Date',
      'expectedArrival': 'Expected Arrival',
      'actualArrival': 'Actual Arrival',
      'customsClearance': 'Customs Clearance',
      'deliverToCustomer': 'Deliver to Customer',
      'receivePayment': 'Receive Payment',
      'clearCustoms': 'Clear Customs',
      'markDelivered': 'Mark as Delivered',
      'pending': 'Pending',
      'inTransit': 'In Transit',
      'atCustoms': 'At Customs',
      'delivered': 'Delivered',
      'save': 'Save',
      'cancel': 'Cancel',
      'noData': 'No data available',
      'loading': 'Loading...',
      'total': 'Total',
      'pendingPayments': 'Pending Payments',
      'completedDeliveries': 'Completed Deliveries',
      'todayCollections': 'Today\'s Collections',
    },
    'ar': {
      'appTitle': 'شركة الشحن اليمنية',
      'login': 'تسجيل الدخول',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'loginButton': 'دخول',
      'logout': 'خروج',
      'home': 'الرئيسية',
      'dashboard': 'لوحة التحكم',
      'shipments': 'الشحنات',
      'customers': 'العملاء',
      'customs': 'التخليص الجمركي',
      'delivery': 'التسليم',
      'collections': 'التحصيلات',
      'tracking': 'التتبع',
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'language': 'اللغة',
      'incomingShipments': 'الشحنات الواردة',
      'shipmentDetails': 'تفاصيل الشحنة',
      'shipmentNumber': 'رقم الشحنة',
      'status': 'الحالة',
      'customer': 'العميل',
      'origin': 'الميناء المصدر',
      'destination': 'الميناء الوجهة',
      'vessel': 'اسم السفينة',
      'departureDate': 'تاريخ المغادرة',
      'expectedArrival': 'تاريخ الوصول المتوقع',
      'actualArrival': 'تاريخ الوصول الفعلي',
      'customsClearance': 'التخليص الجمركي',
      'deliverToCustomer': 'تسليم للعميل',
      'receivePayment': 'استلام الدفع',
      'clearCustoms': 'إتمام التخليص',
      'markDelivered': 'تحديد كمسلمة',
      'pending': 'قيد الانتظار',
      'inTransit': 'في الطريق',
      'atCustoms': 'بالجمارك',
      'delivered': 'مسلمة',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'noData': 'لا توجد بيانات',
      'loading': 'جاري التحميل...',
      'total': 'الإجمالي',
      'pendingPayments': 'مدفوعات معلقة',
      'completedDeliveries': 'تسليمات مكتملة',
      'todayCollections': 'تحصيلات اليوم',
    },
  };

  static String get(String key, {String? lang}) {
    final language = lang ?? 'en';
    return translations[language]?[key] ?? translations['en']?[key] ?? key;
  }
}