/**
 * Localization Helper - مساعد الترجمة
 */
import 'package:flutter/material.dart';

class Localization {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'appTitle': 'China Shipping',
      'login': 'Login',
      'username': 'Username',
      'password': 'Password',
      'loginButton': 'Sign In',
      'logout': 'Logout',
      'home': 'Home',
      'dashboard': 'Dashboard',
      'shipments': 'Shipments',
      'customers': 'Customers',
      'containers': 'Containers',
      'tracking': 'Tracking',
      'settings': 'Settings',
      'profile': 'Profile',
      'language': 'Language',
      'newShipment': 'New Shipment',
      'shipmentDetails': 'Shipment Details',
      'shipmentNumber': 'Shipment Number',
      'status': 'Status',
      'customer': 'Customer',
      'origin': 'Origin',
      'destination': 'Destination',
      'vessel': 'Vessel',
      'departureDate': 'Departure Date',
      'expectedArrival': 'Expected Arrival',
      'inTransit': 'In Transit',
      'delivered': 'Delivered',
      'pending': 'Pending',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'noData': 'No data available',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'totalShipments': 'Total Shipments',
      'inTransitShipments': 'In Transit',
      'deliveredShipments': 'Delivered',
      'recentShipments': 'Recent Shipments',
      'viewAll': 'View All',
      'sales': 'Sales',
      'invoices': 'Invoices',
      'createInvoice': 'Create Invoice',
      'totalCost': 'Total Cost',
      'sellingPrice': 'Selling Price',
      'profit': 'Profit',
      'selectCustomer': 'Select Customer',
      'selectPort': 'Select Port',
      'containers': 'Containers',
      'addContainer': 'Add Container',
      'containerNumber': 'Container Number',
      'containerType': 'Container Type',
      'sealNumber': 'Seal Number',
      'weight': 'Weight',
      'packageCount': 'Package Count',
      'tracking': 'Tracking',
      'addTracking': 'Add Tracking',
      'eventType': 'Event Type',
      'eventDate': 'Event Date',
      'location': 'Location',
      'description': 'Description',
    },
    'ar': {
      'appTitle': 'شركة الشحن الصينية',
      'login': 'تسجيل الدخول',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'loginButton': 'دخول',
      'logout': 'خروج',
      'home': 'الرئيسية',
      'dashboard': 'لوحة التحكم',
      'shipments': 'الشحنات',
      'customers': 'العملاء',
      'containers': 'الحاويات',
      'tracking': 'التتبع',
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'language': 'اللغة',
      'newShipment': 'شحنة جديدة',
      'shipmentDetails': 'تفاصيل الشحنة',
      'shipmentNumber': 'رقم الشحنة',
      'status': 'الحالة',
      'customer': 'العميل',
      'origin': 'الميناء المصدر',
      'destination': 'الميناء الوجهة',
      'vessel': 'اسم السفينة',
      'departureDate': 'تاريخ المغادرة',
      'expectedArrival': 'تاريخ الوصول المتوقع',
      'inTransit': 'في الطريق',
      'delivered': 'مسلمة',
      'pending': 'قيد الانتظار',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'add': 'إضافة',
      'search': 'بحث',
      'noData': 'لا توجد بيانات',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجاح',
      'totalShipments': 'إجمالي الشحنات',
      'inTransitShipments': 'في الطريق',
      'deliveredShipments': 'مسلمة',
      'recentShipments': 'الشحنات الأخيرة',
      'viewAll': 'عرض الكل',
      'sales': 'مبيعات',
      'invoices': 'فواتير',
      'createInvoice': 'إنشاء فاتورة',
      'totalCost': 'التكلفة الإجمالية',
      'sellingPrice': 'سعر البيع',
      'profit': 'الربح',
      'selectCustomer': 'اختر العميل',
      'selectPort': 'اختر الميناء',
      'containers': 'الحاويات',
      'addContainer': 'إضافة حاوية',
      'containerNumber': 'رقم الحاوية',
      'containerType': 'نوع الحاوية',
      'sealNumber': 'رقم الختم',
      'weight': 'الوزن',
      'packageCount': 'عدد الطرود',
      'tracking': 'التتبع',
      'addTracking': 'إضافة تتبع',
      'eventType': 'نوع الحدث',
      'eventDate': 'تاريخ الحدث',
      'location': 'الموقع',
      'description': 'الوصف',
    },
    'zh': {
      'appTitle': '中远物流',
      'login': '登录',
      'username': '用户名',
      'password': '密码',
      'loginButton': '登录',
      'logout': '退出',
      'home': '首页',
      'dashboard': '仪表板',
      'shipments': '货运',
      'customers': '客户',
      'containers': '集装箱',
      'tracking': '追踪',
      'settings': '设置',
      'profile': '个人资料',
      'language': '语言',
      'newShipment': '新货运',
      'shipmentDetails': '货运详情',
      'shipmentNumber': '货运编号',
      'status': '状态',
      'customer': '客户',
      'origin': '起运港',
      'destination': '目的港',
      'vessel': '船名',
      'departureDate': '出发日期',
      'expectedArrival': '预计到达',
      'inTransit': '运输中',
      'delivered': '已交付',
      'pending': '待处理',
      'save': '保存',
      'cancel': '取消',
      'delete': '删除',
      'edit': '编辑',
      'add': '添加',
      'search': '搜索',
      'noData': '暂无数据',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'totalShipments': '总货运量',
      'inTransitShipments': '运输中',
      'deliveredShipments': '已交付',
      'recentShipments': '最近货运',
      'viewAll': '查看全部',
      'sales': '销售',
      'invoices': '发票',
      'createInvoice': '创建发票',
      'totalCost': '总成本',
      'sellingPrice': '售价',
      'profit': '利润',
      'selectCustomer': '选择客户',
      'selectPort': '选择港口',
      'containers': '集装箱',
      'addContainer': '添加集装箱',
      'containerNumber': '集装箱号',
      'containerType': '箱型',
      'sealNumber': '封号',
      'weight': '重量',
      'packageCount': '件数',
      'tracking': '追踪',
      'addTracking': '添加追踪',
      'eventType': '事件类型',
      'eventDate': '事件日期',
      'location': '位置',
      'description': '描述',
    },
  };

  static String get(String key, {String? lang}) {
    final language = lang ?? 'en';
    return translations[language]?[key] ?? translations['en']?[key] ?? key;
  }
}